site_name: "basin3d_schema"
theme:
  name: material
  analytics:
    gtag: G-2SYBSJVZ23
#  palette:
#    scheme: slate
#    primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
nav:
#  - Home: home.md
  - Index: index.md
  - README: README.md
site_url: https://cmungall.github.io/basin3d_schema
repo_url: https://github.com/cmungall/basin3d_schema
